#!/bin/bash

if [ -z "$LAI_ENV_PATH" ]
then
    echo "You need to set the LAI_ENV_PATH variable"
    echo "with the absolute path to the virtualenv dir"
    exit 1
fi

if [ -z "$LAI_MODULE_PATH" ]
then
    echo "You need to set the LAI_MODULE_PATH variable"
    echo "with the absolute path to the laiserver module"
    exit 1
fi

# Export path for virtualenv
export PYTHONPATH=$LAI_MODULE_PATH

# Activate virtualenv
source $LAI_ENV_PATH/bin/activate

# Run the server
python $LAI_MODULE_PATH/laiserver/server.py "$@"

# Finally..
deactivate
